### ISSUE TITLE
Missing screenshots in the plugin repository

### ISSUE THREAD

**Issue by ramiy** [johnjamesjacoby/post-type-switcher#3]
@johnjamesjacoby

I add 3 screenshots in 335178797d80b73617bac2ce98f3ff1b6b9241e7. But in ec6e697117d0b317b6107113bf0de301e56780f1 you moved them to `/assets/screenshots/` sub-folder.

WordPress requires the screenshots to be in the main folder. This why we don't see the images in the plugin repo "screenshots" page: https://wordpress.org/plugins/post-type-switcher/screenshots/

**Comment by johnjamesjacoby** [comment]
Sorry about that, and thanks for the heads up.

I moved the screenshots into the `assets` directory for WordPress.org, so that will fix the plugin there.

I think it's okay to not include those assets in the plugin anymore, too.

**Comment by ramiy** [comment]
@johnjamesjacoby, one last thing,

you should change the screenshots mime-type to **image/png**.

Currently, when clicking the images the browser downloads the image instead of showing the image file.
