### ISSUE TITLE
Only change post type for the first post

### ISSUE THREAD

**Issue by rayrutjes** [johnjamesjacoby/post-type-switcher#5]
Hi there,

Your plugin leads to a lot of confusion when we actually try to create new posts in reaction to a post save.

Here is a scenario that breaks:
- I save a post of type 'post'
- My custom plugin listens on the 'save_post' action hook and creates a custom post of type 'custom_log'
- My custom post type 'custom_log' gets overridden and is saved as 'post' instead.

An easy fix would be to store a static counter that would allow to only override the post type on the first call.

WDYT?

Update: We could also safely bail 'private' post types which would also solve my issue.

**Comment by rayrutjes** [comment]
Any opinion on this @johnjamesjacoby ?

**Comment by johnjamesjacoby** [comment]
Maybe?

The issue as I see it here, is that adding a new post on the `save_post` action is setting the rest of the environment up for recursion issues. I also understand that there isn't currently an easier way to do what you describe with the same level of accuracy.

When I've done similar in the past, I unhooked all actions from `save_post` before running my logger, and readied them when my logger was complete. It's not fool-proof, but it's close. Also, this plugin does try to be "smart" with what types of posts it targets, meaning internal or private types should be unaffected. Activity logs might be better off as internal, or maybe there's something to tweak there.

If all else fails and none of those are viable options, implementing a counter would not be difficult. It could be done easily in a local static variable, but it would need to be aware of and allow bulk actions to still take place via things like Quick Edit.

What I'd like to avoid is making too many assumptions about post relationships, at least until something more than `post_parent` exists. It's impossible to discern how one post truly relates to another, especially when postmeta can be used arbitrarily.

I'll give this a think and look around for any other, better alternatives.

**Comment by rayrutjes** [comment]
Hi @johnjamesjacoby , thx a lot for your feedback here.
I think I will dig into the removal of all hooks bound to `post_save`, this seems like a way to make our plugin better isolated from side effects.

Regarding your plugin, I'm not sure what the best option would be, and I'm sure you have a better overview of the saving lifecycle than I have. I totally get your point about not making any assumptions about the post types, and in that regard I think that is our responsibility to make sure we de-register hooks.

**Comment by johnjamesjacoby** [comment]
Sounds good @rayrutjes. Thanks for the update. Stay in touch if there's anything more you think we can do here, too. The goal is always maximum compatibility with all environments and plugins, and obviously retaining 100% data integrity. When that doesn't happen (and this plugin particularly sensitive to that) it's always a priority.

**Comment by rayrutjes** [comment]
Thx for your inputs ;)
